# <p style="color:blue">Numpy </p>  
-  NumPy is a library written for scientific computing and data analysis. It stands for Numerical Python.
-  it consists of high performance multidimensional arrays
-  tools for Integrates with C/C++
-  functions for linear algebra
-  Fourier series
-  random number genaration functionality
-  list limitations >> Inability to oparate the entire data togather
-  numpy arrays >> alternative to lists

**NumPy** is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```array```, which is **homogenous** in nature. By homogenous, all the elements in a numpy array have to be of the **same data type**, which is commonly numeric (float or integer). 

There are two ways to create NumPy arrays:

-  <b>Converting</b> the existing lists or tuples to arrays using np.array
-  <b>Initialising</b> fixed-length arrays using the NumPy functions

### Numpy vs Lists 

In [4]:
# intialise a list with the following elements: 1, 2, 3, 4, 5
l = [1,2,3,4,5]

# try to multiply 2.5 directly to the created list
for i in l:
    print(i*2.5)
new_list = [i*2.5 for i in l ]
print(new_list)

2.5
5.0
7.5
10.0
12.5
[2.5, 5.0, 7.5, 10.0, 12.5]


Lists cannot operate over the entire data together. You need to run _map_ or _apply_ functions to multiply each element with 2.5. Let's try to perform this using a NumPy array.

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

In [6]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np


In [7]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array

np_l = np.array(l)

In [9]:
# Multiply each element with 2.5 

np_l *2.5

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [11]:
# Print the result using the print command. Compare the structure of list and array.
print(np_l*2.5)

[ 2.5  5.   7.5 10.  12.5]


In [14]:
# Create a 1-D array using with the elements (1, abc, True)
arr = np.array([1,'abc', True])
print(arr)

['1' 'abc' 'True']


You can see above that the elements are of single data type. The numerical and the boolean value is converted to string. 

### Operations over Arrays
One thing to note here is that NumPy comes with its own set of methods and operations. You should not assume that the operators will work in the same way as lists. Look at the example below.

In [15]:
# Create 2 lists with elements (1, 2, 3) and (4, 5, 6)
list1 = [1,2,3]
list2 = [4,5,6]

# Use the '+' operator and print the results
list1+list2


[1, 2, 3, 4, 5, 6]

In [16]:
# Convert the above lists to arrays and use the '+' operator

np_1 =np.array(list1) 
np_2 = np.array(list2)
np_1+np_2

array([5, 7, 9])