# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [2]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(1,6)
arr_2 = np.arange(5,10)


In [6]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2,12))

array([ 1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 12])

In [9]:
# Vertical stacking - Increasing the number of row

np.vstack((arr_1,arr_2))
# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))
arr_3

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [10]:
# Checking the dimensions of the array
arr_3.ndim

2

In [27]:
# Printing the created array
arr_3

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [12]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [13]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [16]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(4,5)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [19]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 5

In [20]:
# Check the structure of arr_6
arr_6.shape

(4, 5)

In [24]:
arr_5.shape

(5, 2)

In [25]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = arr_6.reshape(10,2)
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [26]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])